---
  - name: Setup Samba Service
    hosts: ubuntu

    tasks:
      - name: Install Samba Service
        apt:
         name: samba
         state: latest

      - name: Start Samba Service
        service:
           name: "{{ item }}"
           state: started
        with_item:
           - 'smbd'
           - 'nmbd'
     