---
  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name:
    shell:
      cmd: echo "<h1><center> Sedang belajar roles di ansible </h1></center>" > /var/www/html/index.html

  - name: Restart nginx
    service:
      name: nginx
      state: restarted