# This is the network config written by 'subiquity'
network:
  ethernets:
    ens160:
      dhcp4: false
      #      addresses: [10.23.1.218/22]
      #      gateway4: 10.23.0.1
      #      nameservers:
      #       addresses: [1.1.1.1,8.8.8.8]
  version: 2

  bridges:
     br0:
      interfaces: [ens160]
      addresses: [10.23.1.218/22]
      gateway4: 10.23.0.1
      mtu: 1500
      nameservers:
        addresses: [8.8.8.8]

~                                         